# Logging settings
[logging]
file_path = 'logs/api.log'
level = "INFO"
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> [<bold>{level.icon}<level>{level}</level></bold>] <magenta>{name}</magenta> - {message}"
rotation = "1 day"
enqueue = "True"
colorize = "True"

[models]
execution_provider = "CPUExecutionProvider"
default = "SWINV2_MODEL_DSV3_REPO_Quantized8"
allow_all_images = true